name: jishnu

on:
  workflow_dispatch:

env:
  APP_ENV: jishnu

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment name
        run: echo "Environment:$APP_ENV"

  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/java-21
    steps:
      - name: Print Java home
        run: echo "Java is installed at $JAVA_HOME"
