name: jishnu
on: 
  workflow_dispatch:
env: 
 APP_ENV: jishnu
jobs:
 first-job:
  runs-on: ubuntu-latest
  steps:
    - name: firsst step
      run: echo "my name is $APP_ENV"

 shiyas:
  runs-on: ubuntu-latest
  env:
   JAVA_HOME: /usr/lib/jvm/java-21
  steps:
   - name: demo
     run: echo "Java is installed at $JAVA_HOME"



     
